### ISSUE TITLE
Importing a client fails with a panic

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi-auth0#139]
### What happened?

Trying to import a client:

```
pulumi import auth0:index/client:Client aws
```

Gets an error:

```
Diagnostics:
  pulumi:pulumi:Stack (aws-sso-production):
    panic: interface conversion: interface {} is nil, not map[string]interface {}
    goroutine 30 [running]:
    github.com/auth0/terraform-provider-auth0/auth0.flattenClientAddons(0xc000b4c030)
    	/home/runner/go/pkg/mod/github.com/auth0/terraform-provider-auth0@v0.29.0/auth0/resource_auth0_client.go:997 +0xbdd
    github.com/auth0/terraform-provider-auth0/auth0.readClient(0xc000438230, {0x1eac9e0, 0xc00082cf00})
    	/home/runner/go/pkg/mod/github.com/auth0/terraform-provider-auth0@v0.29.0/auth0/resource_auth0_client.go:640 +0x10db
    github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Refresh(0xc0003f98c0, 0xc00062adc0, {0x1eac9e0, 0xc00082cf00})
    	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.16.1/helper/schema/resource.go:516 +0x1df
    github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Refresh(0xc000566380, 0xc0008df690, 0x10)
    	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.16.1/helper/schema/provider.go:333 +0x65
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v1.v1Provider.Refresh({0xc0008df870}, {0x200a529, 0xc000566400}, {0x22b97b8, 0xc000465f00})
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.20.0/pkg/tfshim/sdk-v1/provider.go:102 +0x99
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*Provider).Read(0xc00080e6c0, {0x22b8788, 0xc0006155f0}, 0xc00062aa50)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.20.0/pkg/tfbridge/provider.go:941 +0x651
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Read_Handler.func1({0x22b8788, 0xc0006155f0}, {0x1f85720, 0xc00062aa50})
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.27.0/proto/go/provider.pb.go:2647 +0x7b
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x22b8788, 0xc000615380}, {0x1f85720, 0xc00062aa50}, 0xc0004e20c0, 0xc00000c468)
    	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x425
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Read_Handler({0x1fc6de0, 0xc00080e6c0}, {0x22b8788, 0xc000615380}, 0xc00096e4e0, 0xc0004e2fe0)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.27.0/proto/go/provider.pb.go:2649 +0x138
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc00037da40, {0x22cf8c0, 0xc0001fa600}, 0xc000854120, 0xc000856330, 0x2c9eed8, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:1217 +0xc8f
    google.golang.org/grpc.(*Server).handleStream(0xc00037da40, {0x22cf8c0, 0xc0001fa600}, 0xc000854120, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:1540 +0xa2a
    google.golang.org/grpc.(*Server).serveStreams.func1.2()
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:878 +0x98
    created by google.golang.org/grpc.(*Server).serveStreams.func1
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:876 +0x294

    error: preview failed

  auth0:index:Client (aws):
    error: Preview failed: transport is closing
```

Same issue if important with the resource option:

```
const app = new auth0.Client("aws", {

}, { import: "<id>"})
```

### Steps to reproduce

- Create an auth0 client
- try and import

### Expected Behavior

It imports

### Actual Behavior

A panic

### Versions used

```
CLI
Version      3.30.0
Go Version   go1.17.9
Go Compiler  gc

Plugins
NAME    VERSION
auth0   2.8.0
aws     5.3.0
docker  3.2.0
nodejs  unknown

Host
OS       darwin
Version  12.3.1
Arch     x86_64

This project is written in nodejs (/Users/lbriggs/.asdf/shims/node v14.16.0)

Current Stack: lbrlabs/production

Found no resources associated with lbrlabs/production

Found no pending operations associated with lbrlabs/production

Backend
Name           pulumi.com
URL            https://app.pulumi.com/jaxxstorm
User           jaxxstorm
Organizations  jaxxstorm, lbrlabs, team-ce, demo, pulumi

NAME            VERSION
@pulumi/awsx    0.40.0
@pulumi/pulumi  3.30.0
@types/node     14.18.16
@pulumi/auth0   2.8.0
@pulumi/aws     5.3.0

Pulumi locates its logs in /var/folders/1y/s9gz0_l10hb2y8mtknj45stc0000gn/T/ by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by guineveresaenger** [comment]
Hi @jaxxstorm - I am struggling to reproduce this at this point in time.

**On v2.8.0 of this provider**

- Created an [example Client following the documentation](https://www.pulumi.com/registry/packages/auth0/api-docs/client/)- removed a few of the bells and whistles for simplicity's sake

```
pulumi about
CLI          
Version      3.78.0
Go Version   go1.20.7
Go Compiler  gc

Plugins
NAME    VERSION
auth0   2.8.0
nodejs  unknown
```
- Ran the import
```
pulumi import auth0:index/client:Client my_client <client_id obtained from console>
[...]
Please copy the following code into your Pulumi application. Not doing so
will cause Pulumi to report that an update will happen on the next update command.

Please note that the imported resources are marked as protected. To destroy them
you will need to remove the `protect` option and run `pulumi update` *before*
the destroy will take effect.

import * as pulumi from "@pulumi/pulumi";
import * as auth0 from "@pulumi/auth0";

const my_client = new auth0.Client("my_client", {
    allowedLogoutUrls: ["https://example.com"],
    allowedOrigins: ["https://example.com"],
    appType: "non_interactive",
    callbacks: ["https://example.com/callback"],
    clientMetadata: {
        foo: "zoo",
    },
    customLoginPageOn: true,
    description: "Test Applications Long Description",
    grantTypes: [
        "authorization_code",
        "http://auth0.com/oauth/grant-type/password-realm",
        "implicit",
        "password",
        "refresh_token",
    ],
    isFirstParty: true,
    isTokenEndpointIpHeaderTrusted: true,
    jwtConfiguration: {
        alg: "RS256",
        lifetimeInSeconds: 300,
        scopes: {
            foo: "bar",
        },
        secretEncoded: true,
    },
    mobile: {
        ios: {
            appBundleIdentifier: "com.my.bundle.id",
            teamId: "9JA89QQLNQ",
        },
    },
    name: "myClient-48368fa",
    refreshToken: {
        expirationType: "non-expiring",
        idleTokenLifetime: 2592000,
        infiniteIdleTokenLifetime: true,
        infiniteTokenLifetime: true,
        rotationType: "non-rotating",
        tokenLifetime: 31557600,
    },
    tokenEndpointAuthMethod: "client_secret_post",
    webOrigins: ["https://example.com"],
}, {
    protect: true,
});
```

I can report an import of a similar basic client (modulo updates to the resource) also works on the latest version of this provider, v2.24.0.

If this issue still persists for you, please feel free to re-open this bug with the relevant details. 🙏
