### ISSUE TITLE
v2.9.0 Expanding tenant "flags" causes pulumi up to fail

### ISSUE THREAD

**Issue by dionfoster** [pulumi/pulumi-auth0#145]
### What happened?

After upgrading @pulumi/auth0 to version 2.9.0, "pulumi up" fails to create a tenant resource with an exception in terraform-provider-auth0@v0.30.2:

```
pulumi:pulumi:Stack (Auth0.Infrastructure-prod-us):
    panic: interface conversion: interface {} is nil, not map[string]interface {}
    goroutine 114 [running]:
    github.com/hashicorp/go-cty/cty.Value.GetAttr({{{0x1800660, 0xc00010c708}}, {0x0, 0x0}}, {0x160fb44, 0x5})
        /home/runner/go/pkg/mod/github.com/hashicorp/go-cty@v1.4.1-0.20200414143053-d3edf31b6320/cty/value_ops.go:711 +0x266
    github.com/auth0/terraform-provider-auth0/auth0.expandTenant(0x12fd0a5)
        /home/runner/go/pkg/mod/github.com/auth0/terraform-provider-auth0@v0.30.2/auth0/resource_auth0_tenant.go:319 +0x31b
    github.com/auth0/terraform-provider-auth0/auth0.updateTenant({0x17ffd30, 0xc000094f60}, 0x20ce400, {0x14e4b60, 0xc000375680})
        /home/runner/go/pkg/mod/github.com/auth0/terraform-provider-auth0@v0.30.2/auth0/resource_auth0_tenant.go:288 +0x45
    github.com/auth0/terraform-provider-auth0/auth0.createTenant({0x17ffd30, 0xc000094f60}, 0xc0005e1580, {0x14e4b60, 0xc000375680})
        /home/runner/go/pkg/mod/github.com/auth0/terraform-provider-auth0@v0.30.2/auth0/resource_auth0_tenant.go:248 +0x6c
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc000381e10, {0x17ffcf8, 0xc00003c0c8}, 0xd, {0x14e4b60, 0xc000375680})
        /home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20220505215311-795430389fa7/helper/schema/resource.go:697 +0x12e
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000381e10, {0x17ffcf8, 0xc00003c0c8}, 0x0, 0xc0004eff80, {0x14e4b60, 0xc000375680})
        /home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20220505215311-795430389fa7/helper/schema/resource.go:827 +0x9ba
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.v2Provider.Apply({0x16126af}, {0x1619353, 0xc}, {0x0, 0x0}, {0x1814708, 0xc0004eff80})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.24.1/pkg/tfshim/sdk-v2/provider.go:112 +0x19c
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*Provider).Create(0xc0000e4900, {0x17ffd68, 0xc0008dee10}, 0xc00044b900)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.24.1/pkg/tfbridge/provider.go:866 +0x647
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Create_Handler.func1({0x17ffd68, 0xc0008dee10}, {0x15a0140, 0xc00044b900})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.33.1/proto/go/provider.pb.go:2614 +0x78
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x17ffd68, 0xc0008dec90}, {0x15a0140, 0xc00044b900}, 0xc00007f9c0, 0xc0008b3f98)
        /home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x406
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Create_Handler({0x15de940, 0xc0000e4900}, {0x17ffd68, 0xc0008dec90}, 0xc000a01020, 0xc0004d48e0)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.33.1/proto/go/provider.pb.go:2616 +0x138
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc000554380, {0x18147c0, 0xc00075e4e0}, 0xc000874000, 0xc00041b500, 0x20bafa0, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.45.0/server.go:1282 +0xccf
    google.golang.org/grpc.(*Server).handleStream(0xc000554380, {0x18147c0, 0xc00075e4e0}, 0xc000874000, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.45.0/server.go:1619 +0xa2a
    google.golang.org/grpc.(*Server).serveStreams.func1.2()
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.45.0/server.go:921 +0x98
    created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.45.0/server.go:919 +0x294
```

### Steps to reproduce

- Create a new auth0 tenant
- Create a tenant with a "flags" configuration set

```
const tenant = new auth0.Tenant("tenantConfig", {
    friendlyName: 'Tenant Name',
    ...
    flags: {
        universalLogin: true
    },
    universalLogin: {
        colors: {
            primary: '#3385ff',
            pageBackground: '#000000'
        }
    }
}, { protect: true });
```

- run pulumi up

### Expected Behavior

Tenant created in the auth0 tenant

### Actual Behavior

Exception expanding tenant "flags" attribute in terraform-provider-auth0@v0.30.2 fails deployment

### Versions used

```
CLI
Version      3.34.0
Go Version   go1.17.11
Go Compiler  gc

Plugins
NAME    VERSION
auth0   2.9.0
nodejs  unknown

Host
OS       Microsoft Windows 10 Pro
Version  10.0.19044 Build 19044
Arch     x86_64

This project is written in nodejs: executable='C:\Program Files\nodejs\node.exe' version='v16.14.0'

Current Stack: INX-Software/prod-us

TYPE                                       URN
pulumi:pulumi:Stack                        urn:pulumi:prod-us::Auth0.Infrastructure::pulumi:pulumi:Stack::Auth0.Infrastructure-prod-us
pulumi:providers:auth0                     urn:pulumi:prod-us::Auth0.Infrastructure::pulumi:providers:auth0::default_2_7_0
auth0:index/prompt:Prompt                  urn:pulumi:prod-us::Auth0.Infrastructure::auth0:index/prompt:Prompt::IdentifierFirst-Prompt
auth0:index/client:Client                  urn:pulumi:prod-us::Auth0.Infrastructure::auth0:index/client:Client::Tenancy-Management
auth0:index/resourceServer:ResourceServer  urn:pulumi:prod-us::Auth0.Infrastructure::auth0:index/resourceServer:ResourceServer::Identity-Api
auth0:index/client:Client                  urn:pulumi:prod-us::Auth0.Infrastructure::auth0:index/client:Client::Platform-Mtm-Client
auth0:index/client:Client                  urn:pulumi:prod-us::Auth0.Infrastructure::auth0:index/client:Client::Identity-Spa
auth0:index/action:Action                  urn:pulumi:prod-us::Auth0.Infrastructure::auth0:index/action:Action::Add-Name-To-Access-Token
auth0:index/resourceServer:ResourceServer  urn:pulumi:prod-us::Auth0.Infrastructure::auth0:index/resourceServer:ResourceServer::InFlight-Mobile-Api
auth0:index/rule:Rule                      urn:pulumi:prod-us::Auth0.Infrastructure::auth0:index/rule:Rule::InFlight-Mobile-Add-Mobile-Number
auth0:index/hook:Hook                      urn:pulumi:prod-us::Auth0.Infrastructure::auth0:index/hook:Hook::Lookup-InFlight-Mobile-User-Hook
auth0:index/client:Client                  urn:pulumi:prod-us::Auth0.Infrastructure::auth0:index/client:Client::InFlight-Mobile-Api-Mtm-Client
auth0:index/tenant:Tenant                  urn:pulumi:prod-us::Auth0.Infrastructure::auth0:index/tenant:Tenant::tenantConfig
auth0:index/client:Client                  urn:pulumi:prod-us::Auth0.Infrastructure::auth0:index/client:Client::InFlight-Mobile-Device-Client
auth0:index/email:Email                    urn:pulumi:prod-us::Auth0.Infrastructure::auth0:index/email:Email::Sendgrid-EmailProvider
auth0:index/client:Client                  urn:pulumi:prod-us::Auth0.Infrastructure::auth0:index/client:Client::Home-Spa
auth0:index/resourceServer:ResourceServer  urn:pulumi:prod-us::Auth0.Infrastructure::auth0:index/resourceServer:ResourceServer::Environment-Api
auth0:index/client:Client                  urn:pulumi:prod-us::Auth0.Infrastructure::auth0:index/client:Client::Environment-Spa
auth0:index/role:Role                      urn:pulumi:prod-us::Auth0.Infrastructure::auth0:index/role:Role::Tenant-Manager-Role
auth0:index/role:Role                      urn:pulumi:prod-us::Auth0.Infrastructure::auth0:index/role:Role::Tenant-Owner-Role
auth0:index/role:Role                      urn:pulumi:prod-us::Auth0.Infrastructure::auth0:index/role:Role::INX-Global-Administrator-Role
auth0:index/clientGrant:ClientGrant        urn:pulumi:prod-us::Auth0.Infrastructure::auth0:index/clientGrant:ClientGrant::Identity-Platform-Mtm-Client-Grant
auth0:index/clientGrant:ClientGrant        urn:pulumi:prod-us::Auth0.Infrastructure::auth0:index/clientGrant:ClientGrant::Platform-Mtm-Client-Grant
auth0:index/clientGrant:ClientGrant        urn:pulumi:prod-us::Auth0.Infrastructure::auth0:index/clientGrant:ClientGrant::InFlight-Mobile-Mtm-Client-Grant
auth0:index/emailTemplate:EmailTemplate    urn:pulumi:prod-us::Auth0.Infrastructure::auth0:index/emailTemplate:EmailTemplate::BlockedAccount-EmailTemplate
auth0:index/emailTemplate:EmailTemplate    urn:pulumi:prod-us::Auth0.Infrastructure::auth0:index/emailTemplate:EmailTemplate::VerificationEmailUsingLink-EmailTemplate
auth0:index/emailTemplate:EmailTemplate    urn:pulumi:prod-us::Auth0.Infrastructure::auth0:index/emailTemplate:EmailTemplate::EnrollInMultifactorAuthentication-EmailTemplate
auth0:index/emailTemplate:EmailTemplate    urn:pulumi:prod-us::Auth0.Infrastructure::auth0:index/emailTemplate:EmailTemplate::UserInvitation-EmailTemplate
auth0:index/emailTemplate:EmailTemplate    urn:pulumi:prod-us::Auth0.Infrastructure::auth0:index/emailTemplate:EmailTemplate::PasswordBreachAlert-EmailTemplate
auth0:index/emailTemplate:EmailTemplate    urn:pulumi:prod-us::Auth0.Infrastructure::auth0:index/emailTemplate:EmailTemplate::VerificationCodeForEmailMFA-EmailTemplate
auth0:index/emailTemplate:EmailTemplate    urn:pulumi:prod-us::Auth0.Infrastructure::auth0:index/emailTemplate:EmailTemplate::VerificationEmailUsingCode-EmailTemplate
auth0:index/emailTemplate:EmailTemplate    urn:pulumi:prod-us::Auth0.Infrastructure::auth0:index/emailTemplate:EmailTemplate::WelcomeEmail-EmailTemplate
auth0:index/emailTemplate:EmailTemplate    urn:pulumi:prod-us::Auth0.Infrastructure::auth0:index/emailTemplate:EmailTemplate::ChangePassword-EmailTemplate
auth0:index/role:Role                      urn:pulumi:prod-us::Auth0.Infrastructure::auth0:index/role:Role::Element-Manager-Role
auth0:index/role:Role                      urn:pulumi:prod-us::Auth0.Infrastructure::auth0:index/role:Role::Element-User-Role
auth0:index/connection:Connection          urn:pulumi:prod-us::Auth0.Infrastructure::auth0:index/connection:Connection::Sms-Connection
auth0:index/connection:Connection          urn:pulumi:prod-us::Auth0.Infrastructure::auth0:index/connection:Connection::Auth0-DB
auth0:index/connection:Connection          urn:pulumi:prod-us::Auth0.Infrastructure::auth0:index/connection:Connection::INX-AD
auth0:index/role:Role                      urn:pulumi:prod-us::Auth0.Infrastructure::auth0:index/role:Role::Element-Reader-Role
auth0:index/clientGrant:ClientGrant        urn:pulumi:prod-us::Auth0.Infrastructure::auth0:index/clientGrant:ClientGrant::Environment-Platform-Mtm-Client-Grant
auth0:index/organization:Organization      urn:pulumi:prod-us::Auth0.Infrastructure::auth0:index/organization:Organization::INX-Org
auth0:index/action:Action                  urn:pulumi:prod-us::Auth0.Infrastructure::auth0:index/action:Action::Product-Availability-Check
auth0:index/triggerBinding:TriggerBinding  urn:pulumi:prod-us::Auth0.Infrastructure::auth0:index/triggerBinding:TriggerBinding::Login-Flow


Found no pending operations associated with INX-Software/prod-us

Backend
Name           pulumi.com
URL            https://app.pulumi.com/dionfoster
User           dionfoster
Organizations  dionfoster, INX-Software
```

### Additional context

It appears that version 2.9.0 of @pulumi/auth0 references pulumi-terraform-bridge v3.21.0 and v0.30.2 of the auth0 Terraform Provider.  

A [change](https://github.com/auth0/terraform-provider-auth0/pull/144) in the way that "flags" are handled in version [v0.30.2](https://github.com/auth0/terraform-provider-auth0/releases/tag/v0.30.2) of the auth0 Terraform Provider appears to have caused this bug.

Rolling back to version 2.7.0 of @pulumi/auth0 was able to get us passed this issue.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by stack72** [comment]
Hi @dionfoster 

My apologies for this - I can already see the issue here! So I can try and figure out a way around this

Paul

**Comment by pebneter** [comment]
Hi there,
I have the exact same error, but I can't change any property of the tenant.
I created the tenant manually, did `pulumi import`, ran `pulumi up` with no changes (and no issues). Then when trying to set `friendly_name="Hello World"` (or any other property), `pulumi up` fails with the error. The preview of the expected changes works well, just not the execution.

**Comment by cookieofcode** [comment]
After updating pulumi_auth0 from 2.8.0 to 2.11.0 (which includes pulumi-terraform-bridge v3.26.1 that should fix the root cause) the following error occurs (no changes):

> error: unmarshaling urn:...$auth0:index/tenant:Tenant$auth0:index/connection:Connection::connection-dev's instance state: could not read field options: '' expected type 'string', got unconvertible type 'map[string]interface {}', value: 'map[]'

**Comment by dionfoster** [comment]
@stack72 as per @cookieofcode's post above, we get the same issue after upgrading to 2.11.0.  It looks like the original issue has been fixed, this looks like something different.  I tried to track the type conversion failure down, but am not terribly familiar with go.

**Comment by rshade** [comment]
@cookieofcode @dionfoster I opened a separate ticket to track this issue. As there is a change in the underlying terraform provider code: https://github.com/pulumi/pulumi-auth0/issues/156

**Comment by dionfoster** [comment]
Thanks, I think we can close this issue then.

**Comment by MoustafaWehbe** [comment]
In my case, I fixed it by the specifying the id of the auth0 connection in the code (I already have the connection created in my tenant). Then run ‘pulumi up’.
