### ISSUE TITLE
SIGSEGV when running Auth0 terraform

### ISSUE THREAD

**Issue by osdiab** [pulumi/pulumi-auth0#159]
### What happened?

As per [this issue](https://github.com/auth0/terraform-provider-auth0/issues/296) I am receiving a segfault whenever I run `pulumi refresh`, even if I remove the `@pulumi/auth0` library altogether. The contributor there says to update the auth0 package, but I don't know how to do that as a lowly web developer. I do see that the version in the provider folder in this package is higher than that of the stack trace below, but i don't know how to bump the version.

### Steps to reproduce

https://app.pulumi.com/spinachhr/web-app/canary/updates/1404

### Expected Behavior

no crash

### Actual Behavior

error 255, crash

### Output of `pulumi about`

```
CLI          
Version      3.38.0
Go Version   go1.19
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host     
OS       darwin
Version  12.5
Arch     x86_64

This project is written in nodejs: executable='/Users/omardiab/.asdf/shims/node' version='v16.15.0'

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/osdiab
User           osdiab
Organizations  osdiab, spinachhr

Pulumi locates its logs in /var/folders/y_/ymxg5jyn2q7514p6mmsm7w_40000gn/T/ by default
warning: Failed to get information about the Pulumi program's dependencies: Could not find either /Users/omardiab/code/spinach/web-app/packages/infra/yarn.lock or /Users/omardiab/code/spinach/web-app/packages/infra/package-lock.json
warning: Failed to get information about the current stack: No current stack
```

we use a yarn workspaces monorepo so that's why it couldn't find lockfiles.

### Additional context

```
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1ce5dfb]
    goroutine 25 [running]:
    github.com/auth0/terraform-provider-auth0/auth0.flattenAuth0Options(0xc00063d7c0)
    	/home/runner/go/pkg/mod/github.com/auth0/terraform-provider-auth0@v0.29.0/auth0/resource_auth0_guardian.go:367 +0x5b
    github.com/auth0/terraform-provider-auth0/auth0.readGuardian(0xc0007ab5f0, {0x1eac9e0, 0xc00063d7c0})
    	/home/runner/go/pkg/mod/github.com/auth0/terraform-provider-auth0@v0.29.0/auth0/resource_auth0_guardian.go:313 +0x2b1
    github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Refresh(0xc0006a7290, 0xc00062ee60, {0x1eac9e0, 0xc00063d7c0})
    	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.16.1/helper/schema/resource.go:516 +0x1df
    github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Refresh(0xc0000f8880, 0xc0005d7690, 0x200cf4a)
    	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.16.1/helper/schema/provider.go:333 +0x65
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v1.v1Provider.Refresh({0xc0001b80a0}, {0x200cf4a, 0xc0000f9300}, {0x22b97b8, 0xc000aae4c0})
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.20.0/pkg/tfshim/sdk-v1/provider.go:102 +0x99
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*Provider).Read(0xc0007b6480, {0x22b8788, 0xc000ae6780}, 0xc00062eaf0)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.20.0/pkg/tfbridge/provider.go:941 +0x651
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Read_Handler.func1({0x22b8788, 0xc000ae6780}, {0x1f85720, 0xc00062eaf0})
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.27.0/proto/go/provider.pb.go:2647 +0x7b
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x22b8788, 0xc000ae6300}, {0x1f85720, 0xc00062eaf0}, 0xc000aca120, 0xc00000c4b0)
    	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x425
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Read_Handler({0x1fc6de0, 0xc0007b6480}, {0x22b8788, 0xc000ae6300}, 0xc00060c420, 0xc000599a80)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.27.0/proto/go/provider.pb.go:2649 +0x138
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc0004b4540, {0x22cf8c0, 0xc0000fa600}, 0xc00055a120, 0xc0007e3050, 0x2c9eed8, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:1217 +0xc8f
    google.golang.org/grpc.(*Server).handleStream(0xc0004b4540, {0x22cf8c0, 0xc0000fa600}, 0xc00055a120, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:1540 +0xa2a
    google.golang.org/grpc.(*Server).serveStreams.func1.2()
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:878 +0x98
    created by google.golang.org/grpc.(*Server).serveStreams.func1
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:876 +0x294
 
    error: preview failed
    ```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by osdiab** [comment]
@stack72 it still seems to be occurring for me. I'm using both pulumi 3.38.0 and the github pulumi action v3, along with `@pulumi/auth0` version `2.13.0`. The logs still show that it's using the `terraform-auth0-provider@v0.29.0`. 

Do I need to do something further to get the underlying terraform provider to use the more recent version? Thanks!

**Comment by stack72** [comment]
Hi @osdiab 

There is no usage of the underlying terraform provider - we extract the CRUD functionality from it and discard it

Are you trying a refresh then and update or just an update?

Paul

**Comment by stack72** [comment]
A refresh will use the current provider - I believe an update will bring you directly onto the new provider version 

Please can you try that?

Paul
