### ISSUE TITLE
Connection refused for Client and ResourceServerScopes

### ISSUE THREAD

**Issue by ollaw** [pulumi/pulumi-auth0#724]
### Describe what happened

The creation of `ResourceServerScopes` or update of `Client` generate the following inline error:
```
auth0:index:ResourceServerScopes (resource-name):
    error: connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:45783: connect: connection refused"
```
and at the end of the stack i get:

```
pulumi:pulumi:Stack (auth0-auth0.staging):
    panic: interface conversion: interface {} is nil, not map[string]interface {}
    goroutine 362 [running]:
    github.com/hashicorp/go-cty/cty.Value.GetAttr({{{0x16be940?, 0xc000724ff8?}}, {0x0?, 0x0?}}, {0x146e19a, 0x2})
    	/home/runner/go/pkg/mod/github.com/hashicorp/go-cty@v1.4.1-0.20200414143053-d3edf31b6320/cty/value_ops.go:711 +0x2d7
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.(*v2InstanceState2).ID(0xc0007962d0?)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.97.0/pkg/tfshim/sdk-v2/provider2.go:92 +0x37
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*Provider).Create(0xc000773988, {0x16be710?, 0xc001029620?}, 0xc0002423f0)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.97.0/pkg/tfbridge/provider.go:1349 +0x9e8
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Create_Handler.func1({0x16be710?, 0xc001029620?}, {0x13cbae0?, 0xc0002423f0?})
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.142.0/proto/go/provider_grpc.pb.go:815 +0xcb
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x16be710, 0xc0010290b0}, {0x13cbae0, 0xc0002423f0}, 0xc001213a80, 0xc00128ed38)
    	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x3db
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Create_Handler({0x14457a0, 0xc000773988}, {0x16be710, 0xc0010290b0}, 0xc001056080, 0xc00061d940)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.142.0/proto/go/provider_grpc.pb.go:817 +0x143
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc000379000, {0x16be710, 0xc001029020}, {0x16c8c40, 0xc00055e000}, 0xc0012158c0, 0xc0000d5500, 0x21d51d8, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.67.1/server.go:1394 +0xe49
    google.golang.org/grpc.(*Server).handleStream(0xc000379000, {0x16c8c40, 0xc00055e000}, 0xc0012158c0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.67.1/server.go:1805 +0xe8b
    google.golang.org/grpc.(*Server).serveStreams.func2.1()
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.67.1/server.go:1029 +0x8b
    created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 26
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.67.1/server.go:1040 +0x125
```

Bumping into this with Pulumi v3.142.0 on Python and pulumi-auth0 v3.10.0. 

### Sample program

```
client = auth0.Client(  ...  )

auth0.ClientCredentials(
    client_id=client.client_id,
     ...
)

auth0.ClientGrant(
    client_id=client.id,
    ....
)
```

### Affected Resource(s)

ResourceServerScopes
Client

### Output of `pulumi about`

CLI          
Version      3.142.0
Go Version   go1.23.3
Go Compiler  gc

Host     
OS       ubuntu
Version  22.04
Arch     x86_64

Backend        
Name           my-hostname
URL            s3://my-bucket
User           my-user
Organizations  
Token type     personal

Pulumi locates its logs in /tmp by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by omar8792** [comment]
Hello, this is also failing for me with the same error, tried with `3.10.0`  and ` 3.9.0`  . Same error.

Code

```
custom_email_provider = auth0.EmailProvider(
    "prima-email-provider",
    name="custom",
    enabled=True,
    default_from_address="no-reply@example.com",
    credentials={},
)
```

**Comment by iwahbe** [comment]
Hi @ollaw. Thanks for opening an issue. I'm not able to repro by updating a client. That works as expected.

My guess is that you have hit https://github.com/pulumi/pulumi-terraform-bridge/issues/2706. I've released a patch version of pulumi-auth0 in case you have. Please let me know if this issue reproduces on the v3.10.1.
